### ISSUE TITLE
garbled text in api?

### ISSUE THREAD

**Issue by srl295** [GothenburgBitFactory/ti.net#21]
https://github.com/GothenburgBitFactory/ti.net/blame/master/content/docs/api.md#L59 has:

> Between the and are the characters U+003A and U+0020.

Between the _what_ and _what_? Was something missing?

**Comment by lauft** [comment]
I believe this should be 

> Between the `key` and the `value` are the characters U+003A (`:`, colon) and U+0020 (` `, space).

**Comment by lauft** [comment]
I restored the documentation. Thanks for spotting it.
