### ISSUE TITLE
Add timew-one-line-summary to the tools page

### ISSUE THREAD

**Issue by vilchy** [GothenburgBitFactory/ti.net#483]
I wrote an extension that displays a short report in a single line (useful for status bars):
https://codeberg.org/vilchy/timew-one-line-summary

I would be happy if you could add it to the tools list.

**Comment by lauft** [comment]
@vilchy Thanks a lot for your contribution! ❤️ 

I have extracted the data from Codeberg 👉🏻 #484 
Feel free to review, otherwise I will merge it as is in the next days.

**Comment by vilchy** [comment]
@lauft Looks good to me. Thanks :)
