### ISSUE TITLE
Tool Request: timewarrior-jirapush

### ISSUE THREAD

**Issue by FoxAmes** [GothenburgBitFactory/ti.net#53]
Hey all,

Love the tool, I've been using it for time logging at work along with TaskWarrior and Bugwarrior for several months now.  For our use case, we dashboard all of our time based on metrics pulled from Jira, so I [wrote a little connector](https://gitlab.com/FoxAmes/timewarrior-jirapush) to upload and tag logs from TimeWarrior.  Not sure if that's the kind of thing that you're looking to include here, but I figured it might be of some use to others in a similar situation.  I prefer working out of GitLab, but I created a read-only mirror [here on GitHub](https://github.com/FoxAmes/timewarrior-jirapush) as it appears the tooling you've built to update the site primarily functions out of GitHub repositories.

**Comment by lauft** [comment]
Thanks for your contribution (and for using Timewarrior)!
Currently, GitLab repositories can only be added manually, scraping GitLab is planned (see #55).
If you know how to use the GitLab API via python, I would be happy if you could share your insights.

BTW: Your tool has been added successfully (see #54)
