### ISSUE TITLE
Docs page should give examples of where timewarrior files are located on different OS's

### ISSUE THREAD

**Issue by rooday-doordash** [GothenburgBitFactory/ti.net#687]
Specifically I was trying to setup the taskwarrior hook for timewarrior following [this doc](https://timewarrior.net/docs/taskwarrior/), where it says:
```
This script is part of the Timewarrior installation, usually at /usr/local/share/doc/timew/ext/on-modify.timewarrior. (However, depending on your system and installation method, you might need to adjust the path to copy from.) 
```

This isn't very useful for those who didn't install it on Linux. E.g. installing on a M3 Mac using homebrew, the location of this script is `/opt/homebrew/share/doc/timew/ext/on-modify.timewarrior` (found the answer [here](https://www.reddit.com/r/taskwarrior/comments/gxp0y2/help_connecting_timewarrior_and_taskwarrior/jbkrvao/)). Can the docs be updated so future folks don't need to dig through reddit comments?

**Comment by lauft** [comment]
@rooday-doordash thanks for the suggestion. I hope [this](https://timewarrior.net/docs/taskwarrior/) is clearer now.

**Comment by rooday-doordash** [comment]
Thanks @lauft, commit looks great! Although I think the GH pages deploy failed so the website hasn't updated: https://github.com/GothenburgBitFactory/ti.net/actions/runs/9324015483/job/25668376557

**Comment by rooday-doordash** [comment]
Ah I see it's deployed now, thanks again for making this change so quickly!
